version: "3.9"
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/StorageDrive/Portainer:/data"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - proxy

  reverse-proxy:
    image: reverseproxy:latest
    ports:
      - "80:80"
    networks:
      - proxy
    volumes:
      - ./data/certs-data/:/data/letsencrypt/
  api:
    image: backend:latest
    volumes:
      - /home/silva/repos/portainer/database:/app/database
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - proxy
  frontend:
    image: freakln/frontend:latest
    ports:
      - "4200:4200"
    networks:
      - proxy

networks:
  proxy:
